name: Deploy Dev Extensions

on:
  workflow_dispatch:

concurrency:
  group: deploy-dev-extensions-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-extensions:
    name: Deploy Dev Extensions
    uses: ./.github/workflows/reusable-deploy-extensions.yml
    secrets: inherit
    with:
      env_name: dev
      account_id: "891377288714"
