# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Replace with the prod Shopify app client ID from the Shopify Dev Dashboard.
client_id = "SHOPIFY_RETAIL_POS_PROD_CLIENT_ID"
name = "Alo Retail POS"
application_url = "https://api.aloyoga.com/pos/v1/"
embedded = true
handle = "alo-retail-pos"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_apps,read_customer_events,read_cart_transforms,write_cart_transforms,read_all_cart_transforms,write_checkouts,read_checkouts,read_custom_fulfillment_services,write_custom_fulfillment_services,read_customers,write_customers,read_discounts_allocator_functions,write_discounts_allocator_functions,write_draft_orders,read_draft_orders,read_gift_cards,write_gift_cards,write_inventory,read_inventory,read_locales,write_locales,write_locations,read_locations,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,write_order_edits,read_order_edits,read_orders,write_orders,read_products,write_products,read_returns,write_returns,read_content,write_content,customer_write_customers,customer_read_customers,customer_read_orders,customer_write_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://api.aloyoga.com/pos/v1/auth/callback",
  "https://api.aloyoga.com/pos/v1/auth/shopify/callback",
  "https://api.aloyoga.com/pos/v1/api/auth/callback"
]

[pos]
embedded = true
