# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e8ffce90bdb1cb538451d4cea754785"
name = "Alo Retail POS Dev"
application_url = "https://api.dev.aloyoga.com/pos/v1/"
embedded = true
handle = "alo-retail-pos-dev"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_users,write_customers,write_draft_orders,write_fulfillments,write_gift_cards,write_inventory,write_order_edits,write_orders,write_products,write_returns"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://api.dev.aloyoga.com/pos/v1/auth/callback",
  "https://api.dev.aloyoga.com/pos/v1/auth/shopify/callback",
  "https://api.dev.aloyoga.com/pos/v1/api/auth/callback"
]

[pos]
embedded = true
