export type CountryEntry = {
  isoCode: string;
  name: string;
  flag: string;
  cities: string[];
};

export const COUNTRIES: CountryEntry[] = [
  { isoCode: "AF", name: "Afghanistan", flag: "🇦🇫", cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"] },
  { isoCode: "AL", name: "Albania", flag: "🇦🇱", cities: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan"] },
  { isoCode: "DZ", name: "Algeria", flag: "🇩🇿", cities: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"] },
  { isoCode: "AD", name: "Andorra", flag: "🇦🇩", cities: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana"] },
  { isoCode: "AO", name: "Angola", flag: "🇦🇴", cities: ["Luanda", "Huambo", "Lubango", "Malanje", "Benguela"] },
  { isoCode: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", cities: ["Saint John's"] },
  { isoCode: "AR", name: "Argentina", flag: "🇦🇷", cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan"] },
  { isoCode: "AM", name: "Armenia", flag: "🇦🇲", cities: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan"] },
  { isoCode: "AU", name: "Australia", flag: "🇦🇺", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Hobart", "Geelong", "Townsville", "Cairns", "Darwin", "Toowoomba"] },
  { isoCode: "AT", name: "Austria", flag: "🇦🇹", cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn"] },
  { isoCode: "AZ", name: "Azerbaijan", flag: "🇦🇿", cities: ["Baku", "Ganja", "Sumqayit", "Mingəçevir", "Nakhchivan"] },
  { isoCode: "BS", name: "Bahamas", flag: "🇧🇸", cities: ["Nassau", "Freeport", "West End"] },
  { isoCode: "BH", name: "Bahrain", flag: "🇧🇭", cities: ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"] },
  { isoCode: "BD", name: "Bangladesh", flag: "🇧🇩", cities: ["Dhaka", "Chittagong", "Sylhet", "Rajshahi", "Khulna", "Comilla", "Mymensingh", "Rangpur", "Barisal", "Narayanganj"] },
  { isoCode: "BB", name: "Barbados", flag: "🇧🇧", cities: ["Bridgetown", "Speightstown", "Oistins"] },
  { isoCode: "BY", name: "Belarus", flag: "🇧🇾", cities: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"] },
  { isoCode: "BE", name: "Belgium", flag: "🇧🇪", cities: ["Brussels", "Antwerp", "Ghent", "Bruges", "Liège", "Namur", "Leuven", "Mons", "Aalst", "Mechelen"] },
  { isoCode: "BZ", name: "Belize", flag: "🇧🇿", cities: ["Belmopan", "Belize City", "San Ignacio", "Orange Walk"] },
  { isoCode: "BJ", name: "Benin", flag: "🇧🇯", cities: ["Cotonou", "Abomey-Calavi", "Porto-Novo", "Parakou", "Djougou"] },
  { isoCode: "BT", name: "Bhutan", flag: "🇧🇹", cities: ["Thimphu", "Phuntsholing", "Paro", "Punakha"] },
  { isoCode: "BO", name: "Bolivia", flag: "🇧🇴", cities: ["Sucre", "La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Oruro", "Potosí", "Tarija", "El Alto"] },
  { isoCode: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", cities: ["Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica"] },
  { isoCode: "BW", name: "Botswana", flag: "🇧🇼", cities: ["Gaborone", "Francistown", "Molepolole", "Serowe", "Kanye"] },
  { isoCode: "BR", name: "Brazil", flag: "🇧🇷", cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís"] },
  { isoCode: "BN", name: "Brunei", flag: "🇧🇳", cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria"] },
  { isoCode: "BG", name: "Bulgaria", flag: "🇧🇬", cities: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven"] },
  { isoCode: "BF", name: "Burkina Faso", flag: "🇧🇫", cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya"] },
  { isoCode: "BI", name: "Burundi", flag: "🇧🇮", cities: ["Bujumbura", "Gitega", "Muyinga", "Ngozi", "Rumonge"] },
  { isoCode: "CV", name: "Cabo Verde", flag: "🇨🇻", cities: ["Praia", "Mindelo", "Santa Maria", "Assomada"] },
  { isoCode: "KH", name: "Cambodia", flag: "🇰🇭", cities: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"] },
  { isoCode: "CM", name: "Cameroon", flag: "🇨🇲", cities: ["Douala", "Yaoundé", "Bamenda", "Bafoussam", "Garoua"] },
  { isoCode: "CA", name: "Canada", flag: "🇨🇦", cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Saskatoon", "Regina"] },
  { isoCode: "CF", name: "Central African Republic", flag: "🇨🇫", cities: ["Bangui", "Bimbo", "Mbaïki", "Berberati"] },
  { isoCode: "TD", name: "Chad", flag: "🇹🇩", cities: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo"] },
  { isoCode: "CL", name: "Chile", flag: "🇨🇱", cities: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán"] },
  { isoCode: "CN", name: "China", flag: "🇨🇳", cities: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu", "Tianjin", "Wuhan", "Xian", "Hangzhou", "Nanjing", "Chongqing", "Suzhou", "Qingdao", "Dongguan", "Shenyang"] },
  { isoCode: "CO", name: "Colombia", flag: "🇨🇴", cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Manizales"] },
  { isoCode: "KM", name: "Comoros", flag: "🇰🇲", cities: ["Moroni", "Mutsamudu", "Fomboni"] },
  { isoCode: "CG", name: "Congo", flag: "🇨🇬", cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi"] },
  { isoCode: "CD", name: "Congo (DRC)", flag: "🇨🇩", cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Goma", "Bukavu", "Kananga", "Kisangani"] },
  { isoCode: "CR", name: "Costa Rica", flag: "🇨🇷", cities: ["San José", "Cartago", "Heredia", "Alajuela", "Liberia"] },
  { isoCode: "CI", name: "Cote d'Ivoire", flag: "🇨🇮", cities: ["Abidjan", "Yamoussoukro", "Bouaké", "Daloa", "Korhogo"] },
  { isoCode: "HR", name: "Croatia", flag: "🇭🇷", cities: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Karlovac", "Sisak"] },
  { isoCode: "CU", name: "Cuba", flag: "🇨🇺", cities: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara"] },
  { isoCode: "CY", name: "Cyprus", flag: "🇨🇾", cities: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"] },
  { isoCode: "CZ", name: "Czech Republic", flag: "🇨🇿", cities: ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc", "České Budějovice", "Hradec Králové", "Ústí nad Labem"] },
  { isoCode: "DK", name: "Denmark", flag: "🇩🇰", cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle"] },
  { isoCode: "DJ", name: "Djibouti", flag: "🇩🇯", cities: ["Djibouti City", "Ali Sabieh", "Dikhil", "Tadjoura"] },
  { isoCode: "DO", name: "Dominican Republic", flag: "🇩🇴", cities: ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "San Pedro de Macorís", "Puerto Plata"] },
  { isoCode: "EC", name: "Ecuador", flag: "🇪🇨", cities: ["Quito", "Guayaquil", "Cuenca", "Ambato", "Portoviejo", "Manta", "Loja", "Machala"] },
  { isoCode: "EG", name: "Egypt", flag: "🇪🇬", cities: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Suez", "Luxor", "Asyut", "Mansoura", "Tanta"] },
  { isoCode: "SV", name: "El Salvador", flag: "🇸🇻", cities: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Nueva San Salvador"] },
  { isoCode: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", cities: ["Malabo", "Bata", "Ebebiyín"] },
  { isoCode: "ER", name: "Eritrea", flag: "🇪🇷", cities: ["Asmara", "Keren", "Massawa", "Assab"] },
  { isoCode: "EE", name: "Estonia", flag: "🇪🇪", cities: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"] },
  { isoCode: "SZ", name: "Eswatini", flag: "🇸🇿", cities: ["Mbabane", "Manzini", "Lobamba"] },
  { isoCode: "ET", name: "Ethiopia", flag: "🇪🇹", cities: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Hawassa", "Bahir Dar", "Dessie", "Jimma"] },
  { isoCode: "FJ", name: "Fiji", flag: "🇫🇯", cities: ["Suva", "Nadi", "Lautoka", "Labasa"] },
  { isoCode: "FI", name: "Finland", flag: "🇫🇮", cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyvaskyla", "Lahti", "Kuopio"] },
  { isoCode: "FR", name: "France", flag: "🇫🇷", cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Etienne", "Toulon"] },
  { isoCode: "GA", name: "Gabon", flag: "🇬🇦", cities: ["Libreville", "Port-Gentil", "Franceville", "Oyem"] },
  { isoCode: "GM", name: "Gambia", flag: "🇬🇲", cities: ["Banjul", "Serekunda", "Brikama", "Bakau"] },
  { isoCode: "GE", name: "Georgia", flag: "🇬🇪", cities: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi"] },
  { isoCode: "DE", name: "Germany", flag: "🇩🇪", cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg"] },
  { isoCode: "GH", name: "Ghana", flag: "🇬🇭", cities: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast", "Obuasi", "Tema"] },
  { isoCode: "GR", name: "Greece", flag: "🇬🇷", cities: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Kavala"] },
  { isoCode: "GT", name: "Guatemala", flag: "🇬🇹", cities: ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "San Marcos"] },
  { isoCode: "GN", name: "Guinea", flag: "🇬🇳", cities: ["Conakry", "Nzerekore", "Kindia", "Kankan", "Labe"] },
  { isoCode: "GW", name: "Guinea-Bissau", flag: "🇬🇼", cities: ["Bissau", "Bafata", "Gabu"] },
  { isoCode: "GY", name: "Guyana", flag: "🇬🇾", cities: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina"] },
  { isoCode: "HT", name: "Haiti", flag: "🇭🇹", cities: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes", "Petion-Ville"] },
  { isoCode: "HN", name: "Honduras", flag: "🇭🇳", cities: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "El Progreso"] },
  { isoCode: "HK", name: "Hong Kong", flag: "🇭🇰", cities: ["Hong Kong", "Kowloon", "Tsuen Wan", "Sha Tin", "Tuen Mun", "Yuen Long", "Tai Po", "Fanling"] },
  { isoCode: "HU", name: "Hungary", flag: "🇭🇺", cities: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pecs", "Gyor", "Nyiregyhaza", "Kecskemet"] },
  { isoCode: "IS", name: "Iceland", flag: "🇮🇸", cities: ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Reykjanesbær"] },
  { isoCode: "IN", name: "India", flag: "🇮🇳", cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune", "Jaipur", "Surat", "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Coimbatore"] },
  { isoCode: "ID", name: "Indonesia", flag: "🇮🇩", cities: ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Tangerang", "Depok", "Semarang", "Palembang", "Makassar", "South Tangerang", "Batam", "Pekanbaru", "Bandar Lampung", "Padang"] },
  { isoCode: "IR", name: "Iran", flag: "🇮🇷", cities: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Rasht"] },
  { isoCode: "IQ", name: "Iraq", flag: "🇮🇶", cities: ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah", "Kirkuk", "Najaf", "Karbala"] },
  { isoCode: "IE", name: "Ireland", flag: "🇮🇪", cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray"] },
  { isoCode: "IL", name: "Israel", flag: "🇮🇱", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Holon", "Bnei Brak"] },
  { isoCode: "IT", name: "Italy", flag: "🇮🇹", cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Catania", "Bari", "Venice", "Verona", "Messina", "Padua", "Trieste"] },
  { isoCode: "JM", name: "Jamaica", flag: "🇯🇲", cities: ["Kingston", "Portmore", "Spanish Town", "Montego Bay", "Mandeville"] },
  { isoCode: "JP", name: "Japan", flag: "🇯🇵", cities: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Kobe", "Fukuoka", "Kawasaki", "Kyoto", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai"] },
  { isoCode: "JO", name: "Jordan", flag: "🇯🇴", cities: ["Amman", "Zarqa", "Irbid", "Aqaba", "Russeifa", "Madaba"] },
  { isoCode: "KZ", name: "Kazakhstan", flag: "🇰🇿", cities: ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Ust-Kamenogorsk"] },
  { isoCode: "KE", name: "Kenya", flag: "🇰🇪", cities: ["Nairobi", "Mombasa", "Nakuru", "Eldoret", "Kisumu", "Thika", "Malindi"] },
  { isoCode: "KI", name: "Kiribati", flag: "🇰🇮", cities: ["South Tarawa", "Betio"] },
  { isoCode: "KW", name: "Kuwait", flag: "🇰🇼", cities: ["Kuwait City", "Salmiya", "Hawalli", "Farwaniyah", "Jahra"] },
  { isoCode: "KG", name: "Kyrgyzstan", flag: "🇰🇬", cities: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"] },
  { isoCode: "LA", name: "Laos", flag: "🇱🇦", cities: ["Vientiane", "Luang Prabang", "Savannakhet", "Pakse", "Thakhek"] },
  { isoCode: "LV", name: "Latvia", flag: "🇱🇻", cities: ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala"] },
  { isoCode: "LB", name: "Lebanon", flag: "🇱🇧", cities: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"] },
  { isoCode: "LS", name: "Lesotho", flag: "🇱🇸", cities: ["Maseru", "Teyateyaneng", "Mafeteng", "Leribe"] },
  { isoCode: "LR", name: "Liberia", flag: "🇱🇷", cities: ["Monrovia", "Gbarnga", "Kakata", "Bensonville"] },
  { isoCode: "LY", name: "Libya", flag: "🇱🇾", cities: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Al Khums"] },
  { isoCode: "LI", name: "Liechtenstein", flag: "🇱🇮", cities: ["Vaduz", "Schaan", "Balzers", "Triesen"] },
  { isoCode: "LT", name: "Lithuania", flag: "🇱🇹", cities: ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys"] },
  { isoCode: "LU", name: "Luxembourg", flag: "🇱🇺", cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"] },
  { isoCode: "MO", name: "Macau", flag: "🇲🇴", cities: ["Macau", "Taipa", "Cotai"] },
  { isoCode: "MG", name: "Madagascar", flag: "🇲🇬", cities: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga"] },
  { isoCode: "MW", name: "Malawi", flag: "🇲🇼", cities: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"] },
  { isoCode: "MY", name: "Malaysia", flag: "🇲🇾", cities: ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Kota Kinabalu", "Kuching", "Subang Jaya", "Klang"] },
  { isoCode: "MV", name: "Maldives", flag: "🇲🇻", cities: ["Male", "Addu City", "Fuvahmulah"] },
  { isoCode: "ML", name: "Mali", flag: "🇲🇱", cities: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes"] },
  { isoCode: "MT", name: "Malta", flag: "🇲🇹", cities: ["Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema"] },
  { isoCode: "MH", name: "Marshall Islands", flag: "🇲🇭", cities: ["Majuro", "Ebeye"] },
  { isoCode: "MR", name: "Mauritania", flag: "🇲🇷", cities: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi"] },
  { isoCode: "MU", name: "Mauritius", flag: "🇲🇺", cities: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"] },
  { isoCode: "MX", name: "Mexico", flag: "🇲🇽", cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Leon", "Juarez", "Zapopan", "Nezahualcoyotl", "Merida", "San Luis Potosi", "Aguascalientes", "Hermosillo", "Mexicali", "Culiacan"] },
  { isoCode: "FM", name: "Micronesia", flag: "🇫🇲", cities: ["Palikir", "Weno", "Tofol"] },
  { isoCode: "MD", name: "Moldova", flag: "🇲🇩", cities: ["Chisinau", "Tiraspol", "Balti", "Bender", "Ribnita"] },
  { isoCode: "MC", name: "Monaco", flag: "🇲🇨", cities: ["Monaco", "Monte Carlo", "La Condamine"] },
  { isoCode: "MN", name: "Mongolia", flag: "🇲🇳", cities: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"] },
  { isoCode: "ME", name: "Montenegro", flag: "🇲🇪", cities: ["Podgorica", "Niksic", "Herceg Novi", "Bijelo Polje", "Bar"] },
  { isoCode: "MA", name: "Morocco", flag: "🇲🇦", cities: ["Casablanca", "Rabat", "Fez", "Marrakech", "Agadir", "Tangier", "Meknes", "Oujda", "Kenitra", "Tetouan"] },
  { isoCode: "MZ", name: "Mozambique", flag: "🇲🇿", cities: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"] },
  { isoCode: "MM", name: "Myanmar", flag: "🇲🇲", cities: ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Bago", "Pathein"] },
  { isoCode: "NA", name: "Namibia", flag: "🇳🇦", cities: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund"] },
  { isoCode: "NR", name: "Nauru", flag: "🇳🇷", cities: ["Yaren"] },
  { isoCode: "NP", name: "Nepal", flag: "🇳🇵", cities: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar", "Birgunj", "Dharan"] },
  { isoCode: "NL", name: "Netherlands", flag: "🇳🇱", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort"] },
  { isoCode: "NZ", name: "New Zealand", flag: "🇳🇿", cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua"] },
  { isoCode: "NI", name: "Nicaragua", flag: "🇳🇮", cities: ["Managua", "Leon", "Masaya", "Matagalpa", "Chinandega"] },
  { isoCode: "NE", name: "Niger", flag: "🇳🇪", cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"] },
  { isoCode: "NG", name: "Nigeria", flag: "🇳🇬", cities: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Kaduna", "Enugu", "Ogbomosho", "Onitsha", "Abeokuta", "Warri"] },
  { isoCode: "NO", name: "Norway", flag: "🇳🇴", cities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromso"] },
  { isoCode: "OM", name: "Oman", flag: "🇴🇲", cities: ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "Nizwa", "Sur"] },
  { isoCode: "PK", name: "Pakistan", flag: "🇵🇰", cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Peshawar", "Multan", "Hyderabad", "Islamabad", "Quetta", "Sialkot", "Bahawalpur", "Sargodha", "Jhang"] },
  { isoCode: "PW", name: "Palau", flag: "🇵🇼", cities: ["Ngerulmud", "Koror"] },
  { isoCode: "PA", name: "Panama", flag: "🇵🇦", cities: ["Panama City", "San Miguelito", "Tocumen", "David", "Arraijan"] },
  { isoCode: "PG", name: "Papua New Guinea", flag: "🇵🇬", cities: ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Wewak"] },
  { isoCode: "PY", name: "Paraguay", flag: "🇵🇾", cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiata"] },
  { isoCode: "PE", name: "Peru", flag: "🇵🇪", cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Chimbote", "Huancayo", "Tacna"] },
  { isoCode: "PH", name: "Philippines", flag: "🇵🇭", cities: ["Manila", "Quezon City", "Davao", "Caloocan", "Zamboanga", "Cebu City", "Antipolo", "Pasig", "Taguig", "Valenzuela", "Makati", "Las Pinas", "Bacoor", "Cagayan de Oro"] },
  { isoCode: "PL", name: "Poland", flag: "🇵🇱", cities: ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice", "Bialystok", "Gdynia", "Czestochowa", "Radom", "Sosnowiec"] },
  { isoCode: "PT", name: "Portugal", flag: "🇵🇹", cities: ["Lisbon", "Porto", "Braga", "Coimbra", "Funchal", "Setubal", "Aveiro", "Evora", "Leiria", "Faro"] },
  { isoCode: "QA", name: "Qatar", flag: "🇶🇦", cities: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"] },
  { isoCode: "RO", name: "Romania", flag: "🇷🇴", cities: ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Craiova", "Brasov", "Galati", "Ploiesti", "Oradea"] },
  { isoCode: "RU", name: "Russia", flag: "🇷🇺", cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Omsk", "Chelyabinsk", "Samara", "Ufa", "Rostov-on-Don", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Saratov"] },
  { isoCode: "RW", name: "Rwanda", flag: "🇷🇼", cities: ["Kigali", "Butare", "Gitarama", "Musanze", "Gisenyi"] },
  { isoCode: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", cities: ["Basseterre", "Charlestown"] },
  { isoCode: "LC", name: "Saint Lucia", flag: "🇱🇨", cities: ["Castries", "Bisee", "Vieux Fort"] },
  { isoCode: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", cities: ["Kingstown", "Georgetown", "Barrouallie"] },
  { isoCode: "WS", name: "Samoa", flag: "🇼🇸", cities: ["Apia", "Vaitele", "Faleolo"] },
  { isoCode: "SM", name: "San Marino", flag: "🇸🇲", cities: ["San Marino", "Serravalle", "Borgo Maggiore"] },
  { isoCode: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", cities: ["Sao Tome", "Santo Antonio"] },
  { isoCode: "SA", name: "Saudi Arabia", flag: "🇸🇦", cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Abha", "Buraidah", "Najran"] },
  { isoCode: "SN", name: "Senegal", flag: "🇸🇳", cities: ["Dakar", "Touba", "Thies", "Rufisque", "Kaolack"] },
  { isoCode: "RS", name: "Serbia", flag: "🇷🇸", cities: ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica"] },
  { isoCode: "SC", name: "Seychelles", flag: "🇸🇨", cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
  { isoCode: "SL", name: "Sierra Leone", flag: "🇸🇱", cities: ["Freetown", "Bo", "Kenema", "Makeni"] },
  { isoCode: "SG", name: "Singapore", flag: "🇸🇬", cities: ["Singapore", "Woodlands", "Tampines", "Jurong East", "Sengkang"] },
  { isoCode: "SK", name: "Slovakia", flag: "🇸🇰", cities: ["Bratislava", "Kosice", "Presov", "Nitra", "Zilina"] },
  { isoCode: "SI", name: "Slovenia", flag: "🇸🇮", cities: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"] },
  { isoCode: "SB", name: "Solomon Islands", flag: "🇸🇧", cities: ["Honiara", "Gizo", "Auki"] },
  { isoCode: "SO", name: "Somalia", flag: "🇸🇴", cities: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Berbera"] },
  { isoCode: "ZA", name: "South Africa", flag: "🇿🇦", cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Pietermaritzburg", "Benoni", "Tembisa", "Soweto", "Sandton"] },
  { isoCode: "SS", name: "South Sudan", flag: "🇸🇸", cities: ["Juba", "Wau", "Malakal", "Yei", "Aweil"] },
  { isoCode: "KR", name: "South Korea", flag: "🇰🇷", cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Seongnam", "Goyang", "Yongin", "Bucheon", "Cheongju"] },
  { isoCode: "ES", name: "Spain", flag: "🇪🇸", cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Cordoba", "Valladolid", "Vigo", "Gijon"] },
  { isoCode: "LK", name: "Sri Lanka", flag: "🇱🇰", cities: ["Colombo", "Sri Jayawardenepura Kotte", "Kandy", "Galle", "Jaffna", "Trincomalee", "Negombo"] },
  { isoCode: "SD", name: "Sudan", flag: "🇸🇩", cities: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid"] },
  { isoCode: "SR", name: "Suriname", flag: "🇸🇷", cities: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"] },
  { isoCode: "SE", name: "Sweden", flag: "🇸🇪", cities: ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Orebro", "Linkoping", "Helsingborg", "Jonkoping", "Norrkoping"] },
  { isoCode: "CH", name: "Switzerland", flag: "🇨🇭", cities: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"] },
  { isoCode: "SY", name: "Syria", flag: "🇸🇾", cities: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor"] },
  { isoCode: "TW", name: "Taiwan", flag: "🇹🇼", cities: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Taoyuan", "Keelung", "Chiayi", "Changhua"] },
  { isoCode: "TJ", name: "Tajikistan", flag: "🇹🇯", cities: ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa"] },
  { isoCode: "TZ", name: "Tanzania", flag: "🇹🇿", cities: ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya", "Morogoro", "Zanzibar City", "Tanga"] },
  { isoCode: "TH", name: "Thailand", flag: "🇹🇭", cities: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nakhon Ratchasima", "Hat Yai", "Udon Thani", "Chiang Rai", "Nonthaburi", "Pak Kret"] },
  { isoCode: "TL", name: "Timor-Leste", flag: "🇹🇱", cities: ["Dili", "Baucau", "Maliana"] },
  { isoCode: "TG", name: "Togo", flag: "🇹🇬", cities: ["Lome", "Sokode", "Kara", "Atakpame", "Kpalime"] },
  { isoCode: "TO", name: "Tonga", flag: "🇹🇴", cities: ["Nuku'alofa", "Neiafu", "Haveluloto"] },
  { isoCode: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", cities: ["Port of Spain", "San Fernando", "Arima", "Point Fortin", "Chaguanas"] },
  { isoCode: "TN", name: "Tunisia", flag: "🇹🇳", cities: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabes", "Aryanah"] },
  { isoCode: "TR", name: "Turkey", flag: "🇹🇷", cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin", "Eskisehir", "Diyarbakir", "Samsun", "Denizli", "Adapazari"] },
  { isoCode: "TM", name: "Turkmenistan", flag: "🇹🇲", cities: ["Ashgabat", "Turkmenabat", "Dasoguz", "Mary"] },
  { isoCode: "TV", name: "Tuvalu", flag: "🇹🇻", cities: ["Funafuti"] },
  { isoCode: "UG", name: "Uganda", flag: "🇺🇬", cities: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Entebbe", "Mbale"] },
  { isoCode: "UA", name: "Ukraine", flag: "🇺🇦", cities: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol"] },
  { isoCode: "AE", name: "UAE", flag: "🇦🇪", cities: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"] },
  { isoCode: "GB", name: "UK", flag: "🇬🇧", cities: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Leicester", "Bradford", "Cardiff", "Coventry", "Nottingham", "Kingston upon Hull"] },
  { isoCode: "US", name: "USA", flag: "🇺🇸", cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Nashville", "Boston", "Miami", "Atlanta", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa", "Kansas City", "Omaha", "Cleveland", "Raleigh", "Virginia Beach", "Colorado Springs", "Minneapolis", "Wichita", "Arlington", "Tampa"] },
  { isoCode: "UY", name: "Uruguay", flag: "🇺🇾", cities: ["Montevideo", "Salto", "Paysandu", "Las Piedras", "Rivera"] },
  { isoCode: "UZ", name: "Uzbekistan", flag: "🇺🇿", cities: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Nukus", "Bukhara", "Qarshi"] },
  { isoCode: "VU", name: "Vanuatu", flag: "🇻🇺", cities: ["Port Vila", "Luganville"] },
  { isoCode: "VE", name: "Venezuela", flag: "🇻🇪", cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Maturin", "Ciudad Guayana", "San Cristobal"] },
  { isoCode: "VN", name: "Vietnam", flag: "🇻🇳", cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang", "Buon Ma Thuot", "Vung Tau"] },
  { isoCode: "YE", name: "Yemen", flag: "🇾🇪", cities: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Mukalla"] },
  { isoCode: "ZM", name: "Zambia", flag: "🇿🇲", cities: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Livingstone"] },
  { isoCode: "ZW", name: "Zimbabwe", flag: "🇿🇼", cities: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth"] },
];
