# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
uid = "9a817f5c-a039-3100-897e-19220c0da393faf0e4a0"
type = "ui_extension"
name = "employee-discount"

handle = "employee-discount"
description = "employee-discount"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"


[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
