# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
uid = "5e83f779-00be-64a0-ad60-444f81cdef280e42113e"
type = "ui_extension"
name = "Alo.com"

handle = "alocom"
description = "Alo Common Feature"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
