name: Deploy QA

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-qa
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      env_name: qa
      account_id: "058264160686"
