name: Deploy Prod API

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-prod-api
  cancel-in-progress: false

jobs:
  deploy-api:
    if: ${{ startsWith(github.event.release.tag_name, 'pos-api/') || startsWith(github.event.release.tag_name, 'pos-full/') }}
    name: Deploy API (${{ matrix.region }})
    strategy:
      fail-fast: false
      matrix:
        region:
          - us-east-1
          - us-west-2
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      account_id: "418460385342"
      region: ${{ matrix.region }}
      aws_github_action_role_name: gha-alo-retail-pos-service
      app_name: retail-prod-pos
      ecr_repo_name: retail-prod-pos
      codedeploy_name: retail-prod-pos-codedeploy
      lambda_alias: live
      image_tag: ${{ github.event.release.tag_name }}
      deploy_live: true
      build_target: api
      docker_cache_scope: retail-prod-pos-api-${{ matrix.region }}
      build_args: |
        APP_NAME=pos
        ENV=prod
        REGION=${{ matrix.region }}
    secrets:
      new_relic_license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
