name: Deploy Extensions QA

on:
  workflow_dispatch:
  push:
    branches:
      - "QA*"
    paths:
      - "extensions/**"

concurrency:
  group: deploy-extensions-qa
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-extensions.yml
    secrets: inherit
    with:
      env_name: qa
      account_id: "058264160686"
