name: Deploy Extensions Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop*
    paths:
      - "extensions/**"

concurrency:
  group: deploy-extensions-dev
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-extensions.yml
    secrets: inherit
    with:
      env_name: dev
      account_id: "891377288714"
